security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    users_in_memory: { memory: null }
    users_in_database:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: users_in_database
      # custom_authenticator: App\Security\AppAuthenticator
      logout:
        path: app_logout
        target: index

      # form_login configuration
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: /
        username_parameter: _email
        password_parameter: _password
        enable_csrf: true

  access_control:
    # Rediriger vers /login pour les utilisateurs non connectés
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/forgot, roles: PUBLIC_ACCESS }
    - { path: ^/reset, roles: PUBLIC_ACCESS }
    - { path: ^/confirm, roles: PUBLIC_ACCESS }
    - { path: ^/.*, roles: ROLE_USER }

# Test environment specific settings
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
